igger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x'

- script: dotnet build
  displayName: 'Build the project'

- script: dotnet test
  displayName: 'Run tests'